name: build
on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Marlin
        uses: actions/checkout@v2
        with:
          repository: MarlinFirmware/Marlin
          ref: bugfix-2.0.x

      - name: Check out configuration
        uses: actions/checkout@v2
        with:
          path: marlin-ender3-skr_mini_e3_v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Build
        run: |
          pip install platformio
          cp -v marlin-ender3-skr_mini_e3_v2/*.h Marlin/
          platformio run --environment STM32F103RC_btt_512K

      - name: Upload
        run: |
          pushd .pio/build/STM32F103RC_btt_512K > /dev/null
          curl "${{ secrets.DISTFILES_URL }}" \
              -F "file=@firmware.bin" \
              -F "project=marlin-ender3-skr_mini_e3_v2" \
              -F "version=$(date -u '+%+4Y%m%d%H%M%S')" \
              -F "sha512=$(sha512sum firmware.bin)" \
              -F "extract=false"
          popd > /dev/null
